package com.auto.trade.statemachine;

/** 订单交付事件枚举。 */
public enum DeliveryEvent {

    ORDER_DETECTED,
    NO_GREETING_SCRIPT,
    NO_SUB_ORDER,
    GREETING_SEND_FAILED,
    GREETING_FAILED,
    GREETING_SUCCESS,
    QUEUE_ASSIGNMENT,
    DEQUEUE_ASSIGNMENT,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    OFFER_EXPIRED,
    WORKER_DISCONNECTED,
    START_FAILED,
    QUEUED_OFFER_REJECTED,
    QUEUED_OFFER_EXPIRED,
    QUEUED_START_FAILED,
    QUEUED_WORKER_DISCONNECTED,
    TRADE_COMPLETED,
    GAME_TRADE_COMPLETED,
    TRADE_RETRYABLE_FAILED,
    TRADE_FAILED,
    TRADE_TIMED_OUT,
    TRADE_VERIFICATION_FAILED,
    TRADE_CANCELLED,
    MANUAL_DISPATCH,
    RETRY_GREETING,
    RETRY_ASSIGNMENT,
    RESET_TO_GREETING
}
